name: coc-toml test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [10, 14]

    env:
      NODE_ENV: test

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: |
          curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
      - uses: actions/checkout@v2

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: yarn
        run: |
          yarn --frozen-lockfile
      - name: check format
        run: yarn prettier
      - if: matrix.os == 'macos-latest'
        name: yarn test on macOS
        run: |
          curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
          tar xzf nvim-macos.tar.gz
          export PATH="${PATH}:node_modules/.bin:$(pwd)/nvim-osx64/bin"
          nvim --version
          yarn --frozen-lockfile
      - if: matrix.os == 'ubuntu-latest'
        name: yarn test on Ubuntu
        run: |
          curl -LO https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
          tar xzf nvim-linux64.tar.gz
          export PATH="${PATH}:node_modules/.bin:$(pwd)/nvim-linux64/bin"
          nvim --version
          yarn --frozen-lockfile
        env:
          NODE_ENV: test
